// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.6. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;
pragma experimental ABIEncoderV2;

interface ManagedPoolFactory {

event FactoryDisabled(  ) ;
event PoolCreated( address indexed pool ) ;
function create( ManagedPoolSettings.NewPoolParams memory poolParams,address owner ) external  returns (address pool) ;
function disable(  ) external   ;
function getActionId( bytes4 selector ) external view returns (bytes32 ) ;
function getAuthorizer(  ) external view returns (address ) ;
function getCreationCode(  ) external view returns (bytes memory ) ;
function getCreationCodeContracts(  ) external view returns (address contractA, address contractB) ;
function getPauseConfiguration(  ) external view returns (uint256 pauseWindowDuration, uint256 bufferPeriodDuration) ;
function getProtocolFeePercentagesProvider(  ) external view returns (address ) ;
function getVault(  ) external view returns (address ) ;
function getWeightedMath(  ) external view returns (address ) ;
function isDisabled(  ) external view returns (bool ) ;
function isPoolFromFactory( address pool ) external view returns (bool ) ;
}

interface ManagedPoolSettings {
struct NewPoolParams { string name;
string symbol;
address[] tokens;
uint256[] normalizedWeights;
address[] assetManagers;
uint256 swapFeePercentage;
bool swapEnabledOnStart;
bool mustAllowlistLPs;
uint256 managementAumFeePercentage;
uint256 aumFeeId; }
}
